"""autogenerated by genpy from aidu_mobile_base/State.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class State(genpy.Message):
  _md5sum = "7d9f6213bc26e628ae8b9d8c161c722f"
  _type = "aidu_mobile_base/State"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# This message describes the actual position of the wheel base in radians
float32 leftpos
float32 rightpos
float32 leftspeed
float32 rightspeed


"""
  __slots__ = ['leftpos','rightpos','leftspeed','rightspeed']
  _slot_types = ['float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       leftpos,rightpos,leftspeed,rightspeed

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(State, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.leftpos is None:
        self.leftpos = 0.
      if self.rightpos is None:
        self.rightpos = 0.
      if self.leftspeed is None:
        self.leftspeed = 0.
      if self.rightspeed is None:
        self.rightspeed = 0.
    else:
      self.leftpos = 0.
      self.rightpos = 0.
      self.leftspeed = 0.
      self.rightspeed = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_4f.pack(_x.leftpos, _x.rightpos, _x.leftspeed, _x.rightspeed))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.leftpos, _x.rightpos, _x.leftspeed, _x.rightspeed,) = _struct_4f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_4f.pack(_x.leftpos, _x.rightpos, _x.leftspeed, _x.rightspeed))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.leftpos, _x.rightpos, _x.leftspeed, _x.rightspeed,) = _struct_4f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_4f = struct.Struct("<4f")
